network_subnets:
  Dev:
    vip_subnet: "10.1.1.0/24"
    public_subnet: "100.1.1.0/24"

app_settings:
  Dev:
    API:
      f5_profiles:
        - http
        - tcp
        - name: SSL_CLIENT_DEFAULT
          context: client-side
      pool: POOL_API
      asm_policy: ASM_DEV_API
  Prod:
    API:
      f5_profiles:
        - http
        - tcp
        - name: PROD_API
          context: client-side
      pool: POOL_API
      asm_policy: ASM_PROD_API

mattermost_token: dpd6hwgymidzzfkoca9aheyzhy
mattermost_url: "https://192.168.6.102"

netbox_url: "https://192.168.10.169"

jira_url: "https://macknet.atlassian.net"
