- hosts: all
  gather_facts: false

  tasks:
    - name: Change Jira Ticket Status Successful
      uri:
        url: "https://{{ jira_url }}/rest/api/2/issue/{{ ticket }}/transitions"
        user: "{{ jira_id }}"
        password: "{{ jira_token }}"
        method: POST
        headers:
          Accept: application/json
        body: "{{ lookup('template','jira_success.json') }}"
        force_basic_auth: yes
        status_code: [200, 201, 204]
        body_format: json
      delegate_to: localhost
      run_once: true

    - name: Send Mattermost Success Message
      mattermost:
        url: "{{ mattermost_url }}"
        api_key: "{{ mattermost_token }}"
        channel: netops
        text: "Successfully created {{ f5_vip_name }} for {{ customer_name }}\nTicket: {{ ticket_link }}\nPublic IP: {{ public_ip }}\nPrivate IP: {{ private_ip }}\nJob Details: {{ job_url }}"
        validate_certs: no
      run_once: true
      delegate_to: localhost
