---
- name: Set Workflow ID as Fact
  set_stats:
    data:
      job_url: https://ansible.mackdev.net/#/workflows/{{ tower_workflow_job_id }}

- name: Include Data Assert Tasks
  include_tasks: data_assert.yml

- name: Include Netbox Task
  include_tasks: netbox.yml
